{% set version = "2.0.6" %}

package:
  name: bob.io.image
  version: {{ version }}

source:
  fn: bob.io.image-{{ version }}.zip
  md5: afb398bc1d5737bfed455a301aeb565f
  url: https://pypi.io/packages/source/b/bob.io.image/bob.io.image-{{ version }}.zip

build:
  number: 1
  skip: true  # [not linux]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
  - python
  - setuptools
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base
  - giflib
  - libpng 1.6*
  - jpeg 8*
  - libtiff 4.0.*
  - pkg-config

  run:
  - python
  - bob.extension
  - bob.blitz
  - bob.core
  - bob.io.base
  - giflib
  - libpng 1.6*
  - jpeg 8*
  - libtiff 4.0.*

test:
  commands:
  - nosetests -sv bob.io.image

  imports:
  - bob
  - bob.io
  - bob.io.image

  requires:
  - nose

about:
  home: http://github.com/bioidiap/bob.io.image
  license: Modified BSD License (3-clause)
  summary: Image I/O support for Bob

extra:
  recipe-maintainers:
  - 183amir
